apiVersion: v1
name: frontend-mexicoin
version: 0.1.1
appVersion: 0.1.0
description: Frontend mexicoin Helm chart.
keywords:
- node
- javascript
- nodejs
- git-sync
- helm
maintainers:
- name: David Canillas
  email: dc@grupoptm.com
engine: gotpl
icon: https://bitnami.com/assets/stacks/nodejs/img/nodejs-stack-110x117.png
