apiVersion: v1
name: frontend-sni
version: 0.1.1
appVersion: 0.1.0
description: Frontend SNI Helm chart.
keywords:
- node
- javascript
- nodejs
- git-sync
- helm
maintainers:
- name: José Vázquez
  email: mylo@bigpyx.com
engine: gotpl
icon: https://bitnami.com/assets/stacks/nodejs/img/nodejs-stack-110x117.png
